// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feature_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeatureRequest = `-- name: CreateFeatureRequest :one
INSERT INTO feature_requests (project_id, created_by, title, description)
VALUES ($1::uuid, $2::uuid, $3, $4)
RETURNING id, project_id, created_by, title, description, status, created_at
`

type CreateFeatureRequestParams struct {
	ProjectID   string
	CreatedBy   string
	Title       string
	Description pgtype.Text
}

type CreateFeatureRequestRow struct {
	ID          string
	ProjectID   string
	CreatedBy   string
	Title       string
	Description pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateFeatureRequest(ctx context.Context, arg CreateFeatureRequestParams) (CreateFeatureRequestRow, error) {
	row := q.db.QueryRow(ctx, createFeatureRequest,
		arg.ProjectID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
	)
	var i CreateFeatureRequestRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFeatureRequestByID = `-- name: GetFeatureRequestByID :one
SELECT
    fr.id,
    fr.project_id,
    fr.created_by,
    fr.title,
    fr.description,
    fr.status,
    fr.created_at,
    u.name AS created_by_name,
    p.owner_id AS project_owner_id,
    COALESCE(v.cnt, 0)::int AS upvote_count,
    EXISTS (
        SELECT 1 FROM votes vv
        WHERE vv.feature_request_id = fr.id
          AND vv.user_id = $1::uuid
          AND vv.deleted_at IS NULL
    ) AS viewer_has_voted
FROM feature_requests fr
JOIN users u ON u.id = fr.created_by
JOIN projects p ON p.id = fr.project_id
LEFT JOIN (
    SELECT feature_request_id, count(*) AS cnt
    FROM votes
    WHERE deleted_at IS NULL
    GROUP BY feature_request_id
) v ON v.feature_request_id = fr.id
WHERE fr.id = $2::uuid AND fr.deleted_at IS NULL
`

type GetFeatureRequestByIDParams struct {
	ViewerID string
	ID       string
}

type GetFeatureRequestByIDRow struct {
	ID             string
	ProjectID      string
	CreatedBy      string
	Title          string
	Description    pgtype.Text
	Status         string
	CreatedAt      pgtype.Timestamptz
	CreatedByName  string
	ProjectOwnerID string
	UpvoteCount    int32
	ViewerHasVoted bool
}

func (q *Queries) GetFeatureRequestByID(ctx context.Context, arg GetFeatureRequestByIDParams) (GetFeatureRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getFeatureRequestByID, arg.ViewerID, arg.ID)
	var i GetFeatureRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedByName,
		&i.ProjectOwnerID,
		&i.UpvoteCount,
		&i.ViewerHasVoted,
	)
	return i, err
}

const listFeatureRequests = `-- name: ListFeatureRequests :many
SELECT
    fr.id,
    fr.project_id,
    fr.created_by,
    fr.title,
    fr.description,
    fr.status,
    fr.created_at,
    u.name AS created_by_name,
    COALESCE(v.cnt, 0)::int AS upvote_count,
    EXISTS (
        SELECT 1 FROM votes vv
        WHERE vv.feature_request_id = fr.id
          AND vv.user_id = $1::uuid
          AND vv.deleted_at IS NULL
    ) AS viewer_has_voted
FROM feature_requests fr
JOIN users u ON u.id = fr.created_by
LEFT JOIN (
    SELECT feature_request_id, count(*) AS cnt
    FROM votes
    WHERE deleted_at IS NULL
    GROUP BY feature_request_id
) v ON v.feature_request_id = fr.id
WHERE fr.project_id = $2::uuid
  AND fr.deleted_at IS NULL
  AND ($3::text = '' OR fr.status = $3::text)
  AND (
    $4::bool = false
    OR COALESCE(v.cnt, 0)::int < $5::int
    OR (COALESCE(v.cnt, 0)::int = $5::int AND fr.created_at < $6::timestamptz)
    OR (COALESCE(v.cnt, 0)::int = $5::int AND fr.created_at = $6::timestamptz AND fr.id < $7::uuid)
  )
ORDER BY upvote_count DESC, fr.created_at DESC, fr.id DESC
LIMIT $8::int
`

type ListFeatureRequestsParams struct {
	ViewerID        string
	ProjectID       string
	Status          string
	HasCursor       bool
	CursorCount     int32
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	LimitCount      int32
}

type ListFeatureRequestsRow struct {
	ID             string
	ProjectID      string
	CreatedBy      string
	Title          string
	Description    pgtype.Text
	Status         string
	CreatedAt      pgtype.Timestamptz
	CreatedByName  string
	UpvoteCount    int32
	ViewerHasVoted bool
}

func (q *Queries) ListFeatureRequests(ctx context.Context, arg ListFeatureRequestsParams) ([]ListFeatureRequestsRow, error) {
	rows, err := q.db.Query(ctx, listFeatureRequests,
		arg.ViewerID,
		arg.ProjectID,
		arg.Status,
		arg.HasCursor,
		arg.CursorCount,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeatureRequestsRow
	for rows.Next() {
		var i ListFeatureRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.UpvoteCount,
			&i.ViewerHasVoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureRequestsNewest = `-- name: ListFeatureRequestsNewest :many
SELECT
    fr.id,
    fr.project_id,
    fr.created_by,
    fr.title,
    fr.description,
    fr.status,
    fr.created_at,
    u.name AS created_by_name,
    COALESCE(v.cnt, 0)::int AS upvote_count,
    EXISTS (
        SELECT 1 FROM votes vv
        WHERE vv.feature_request_id = fr.id
          AND vv.user_id = $1::uuid
          AND vv.deleted_at IS NULL
    ) AS viewer_has_voted
FROM feature_requests fr
JOIN users u ON u.id = fr.created_by
LEFT JOIN (
    SELECT feature_request_id, count(*) AS cnt
    FROM votes
    WHERE deleted_at IS NULL
    GROUP BY feature_request_id
) v ON v.feature_request_id = fr.id
WHERE fr.project_id = $2::uuid
  AND fr.deleted_at IS NULL
  AND ($3::text = '' OR fr.status = $3::text)
  AND (
    $4::bool = false
    OR fr.created_at < $5::timestamptz
    OR (fr.created_at = $5::timestamptz AND fr.id < $6::uuid)
  )
ORDER BY fr.created_at DESC, fr.id DESC
LIMIT $7::int
`

type ListFeatureRequestsNewestParams struct {
	ViewerID        string
	ProjectID       string
	Status          string
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	LimitCount      int32
}

type ListFeatureRequestsNewestRow struct {
	ID             string
	ProjectID      string
	CreatedBy      string
	Title          string
	Description    pgtype.Text
	Status         string
	CreatedAt      pgtype.Timestamptz
	CreatedByName  string
	UpvoteCount    int32
	ViewerHasVoted bool
}

func (q *Queries) ListFeatureRequestsNewest(ctx context.Context, arg ListFeatureRequestsNewestParams) ([]ListFeatureRequestsNewestRow, error) {
	rows, err := q.db.Query(ctx, listFeatureRequestsNewest,
		arg.ViewerID,
		arg.ProjectID,
		arg.Status,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeatureRequestsNewestRow
	for rows.Next() {
		var i ListFeatureRequestsNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.UpvoteCount,
			&i.ViewerHasVoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFeatureRequest = `-- name: SoftDeleteFeatureRequest :exec
UPDATE feature_requests
SET deleted_at = now()
WHERE id = $1::uuid AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFeatureRequest(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteFeatureRequest, id)
	return err
}

const updateFeatureRequest = `-- name: UpdateFeatureRequest :one
UPDATE feature_requests
SET title = $1, description = $2
WHERE id = $3::uuid AND deleted_at IS NULL
RETURNING id, project_id, created_by, title, description, status, created_at
`

type UpdateFeatureRequestParams struct {
	Title       string
	Description pgtype.Text
	ID          string
}

type UpdateFeatureRequestRow struct {
	ID          string
	ProjectID   string
	CreatedBy   string
	Title       string
	Description pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateFeatureRequest(ctx context.Context, arg UpdateFeatureRequestParams) (UpdateFeatureRequestRow, error) {
	row := q.db.QueryRow(ctx, updateFeatureRequest, arg.Title, arg.Description, arg.ID)
	var i UpdateFeatureRequestRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateFeatureRequestStatus = `-- name: UpdateFeatureRequestStatus :one
UPDATE feature_requests
SET status = $1
WHERE id = $2::uuid AND deleted_at IS NULL
RETURNING id, project_id, created_by, title, description, status, created_at
`

type UpdateFeatureRequestStatusParams struct {
	Status string
	ID     string
}

type UpdateFeatureRequestStatusRow struct {
	ID          string
	ProjectID   string
	CreatedBy   string
	Title       string
	Description pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateFeatureRequestStatus(ctx context.Context, arg UpdateFeatureRequestStatusParams) (UpdateFeatureRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, updateFeatureRequestStatus, arg.Status, arg.ID)
	var i UpdateFeatureRequestStatusRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
