// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.owner_id,
    p.name,
    p.slug,
    p.description,
    p.created_at,
    u.name AS owner_name
FROM projects p
JOIN users u ON u.id = p.owner_id
WHERE p.deleted_at IS NULL
  AND (
    $1::bool = false
    OR p.created_at < $2::timestamptz
    OR (p.created_at = $2::timestamptz AND p.id < $3::uuid)
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $4::int
`

type ListProjectsParams struct {
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	LimitCount      int32
}

type ListProjectsRow struct {
	ID          string
	OwnerID     string
	Name        string
	Slug        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	OwnerName   string
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT
    p.id,
    p.owner_id,
    p.name,
    p.slug,
    p.description,
    p.created_at,
    u.name AS owner_name
FROM projects p
JOIN users u ON u.id = p.owner_id
WHERE p.deleted_at IS NULL
  AND p.owner_id = $1::uuid
  AND (
    $2::bool = false
    OR p.created_at < $3::timestamptz
    OR (p.created_at = $3::timestamptz AND p.id < $4::uuid)
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $5::int
`

type ListProjectsByOwnerParams struct {
	OwnerID         string
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	LimitCount      int32
}

type ListProjectsByOwnerRow struct {
	ID          string
	OwnerID     string
	Name        string
	Slug        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	OwnerName   string
}

func (q *Queries) ListProjectsByOwner(ctx context.Context, arg ListProjectsByOwnerParams) ([]ListProjectsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner,
		arg.OwnerID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByOwnerRow
	for rows.Next() {
		var i ListProjectsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
