// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package db

import (
	"context"
)

const createVote = `-- name: CreateVote :exec
INSERT INTO votes (feature_request_id, user_id)
VALUES ($1::uuid, $2::uuid)
`

type CreateVoteParams struct {
	FeatureRequestID string
	UserID           string
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) error {
	_, err := q.db.Exec(ctx, createVote, arg.FeatureRequestID, arg.UserID)
	return err
}

const removeVote = `-- name: RemoveVote :exec
UPDATE votes
SET deleted_at = now()
WHERE feature_request_id = $1::uuid
  AND user_id = $2::uuid
  AND deleted_at IS NULL
`

type RemoveVoteParams struct {
	FeatureRequestID string
	UserID           string
}

func (q *Queries) RemoveVote(ctx context.Context, arg RemoveVoteParams) error {
	_, err := q.db.Exec(ctx, removeVote, arg.FeatureRequestID, arg.UserID)
	return err
}
